fullname = ( environment == "testing") ? "${registry}/postgis-testing" : "${registry}/postgis"
url = "https://github.com/cloudnative-pg/postgis-containers"

// MANUALLY EDIT THE CONTENT - to add new PostGIS major version
variable "postgisMajorVersions" {
  default = [
    "3"
  ]
}

// DO NOT MANUALLY EDIT THE CONTENT - This is auto-generated by postgis_update.yml
// PostGIS matrix of distro x versions
postgisMatrix = {
  bookworm = {
    "3" = "3.6.0+dfsg-3.pgdg12+1"
  }
  trixie = {
    "3" = "3.6.0+dfsg-3.pgdg13+1"
  }
}

variable "distributions" {
  default = [
    "bookworm",
    "trixie"
  ]
}

variable "imageTypes" {
  default = [
    "standard",
    "system"
  ]
}

target "postgis" {
  matrix = {
    tgt = imageTypes
    distro = distributions
    postgisMajor = postgisMajorVersions
    pgVersion = getPgVersions(postgreSQLVersions, postgreSQLPreviewVersions)
  }

  platforms = [
    "linux/amd64",
    "linux/arm64"
  ]
  dockerfile = "cwd://Dockerfile"
  context = "."
  name = "postgis-${postgisMajor}-${index(split(".",cleanVersion(pgVersion)),0)}-${tgt}-${distro}"
  tags = [
    "${fullname}:${index(split(".",cleanVersion(pgVersion)),0)}-${postgisMajor}-${tgt}-${distro}",
    "${fullname}:${index(split(".",cleanVersion(pgVersion)),0)}-${getShortPostgisVersion(distro, postgisMajor)}-${tgt}-${distro}",
    "${fullname}:${cleanVersion(pgVersion)}-${getPostgisVersion(distro, postgisMajor)}-${tgt}-${distro}",
    "${fullname}:${cleanVersion(pgVersion)}-${getPostgisVersion(distro, postgisMajor)}-${formatdate("YYYYMMDDhhmm", now)}-${tgt}-${distro}",
  ]
  args = {
    PG_MAJOR = "${getMajor(pgVersion)}"
    POSTGIS_VERSION = "${getPostgisPackage(distro, postgisMajor)}"
    POSTGIS_MAJOR = postgisMajor
    BASE = "${getBaseImage(pgVersion, tgt, distro)}"
  }
  attest = [
    "type=provenance,mode=max",
    "type=sbom"
  ]
  annotations = [
    "index,manifest:org.opencontainers.image.created=${now}",
    "index,manifest:org.opencontainers.image.url=${url}",
    "index,manifest:org.opencontainers.image.source=${url}",
    "index,manifest:org.opencontainers.image.version=${pgVersion}-${getPostgisVersion(distro, postgisMajor)}",
    "index,manifest:org.opencontainers.image.revision=${revision}",
    "index,manifest:org.opencontainers.image.vendor=${authors}",
    "index,manifest:org.opencontainers.image.title=CloudNativePG PostGIS ${pgVersion}-${getPostgisVersion(distro, postgisMajor)} ${tgt}",
    "index,manifest:org.opencontainers.image.description=A ${tgt} PostGIS ${pgVersion}-${getPostgisVersion(distro, postgisMajor)} container image",
    "index,manifest:org.opencontainers.image.documentation=${url}",
    "index,manifest:org.opencontainers.image.authors=${authors}",
    "index,manifest:org.opencontainers.image.licenses=Apache-2.0",
    "index,manifest:org.opencontainers.image.base.name=${getBaseImage(pgVersion, tgt, distro)}",
  ]
  labels = {
    "org.opencontainers.image.created" = "${now}",
    "org.opencontainers.image.url" = "${url}",
    "org.opencontainers.image.source" = "${url}",
    "org.opencontainers.image.version" = "${pgVersion}",
    "org.opencontainers.image.revision" = "${revision}",
    "org.opencontainers.image.vendor" = "${authors}",
    "org.opencontainers.image.title" = "CloudNativePG PostGIS ${pgVersion}-${getPostgisVersion(distro, postgisMajor)} ${tgt}",
    "org.opencontainers.image.description" = "A ${tgt} PostGIS ${pgVersion}-${getPostgisVersion(distro, postgisMajor)} container image",
    "org.opencontainers.image.documentation" = "${url}",
    "org.opencontainers.image.authors" = "${authors}",
    "org.opencontainers.image.licenses" = "Apache-2.0"
    "org.opencontainers.image.base.name" = "${getBaseImage(pgVersion, tgt, distro)}"
  }
}

function getBaseImage {
  params = [ pgVersion, imageType, distro ]
  result = format("ghcr.io/cloudnative-pg/postgresql:%s-%s-%s", cleanVersion(pgVersion), imageType, distro)
}

function getPostgisPackage {
  params = [distro, postgisMajor]
  result = postgisMatrix[distro][postgisMajor]
}

// Gets the MM.mm.pp postgis version, e.g. "3.6.0"
function getPostgisVersion {
  params = [ distro, postgisMajor ]
  result = join(".", slice(split(".", split("+", getPostgisPackage(distro, postgisMajor))[0]), 0, 3))
}

// Gets the MM.mm postgis version, e.g. "3.6"
function getShortPostgisVersion {
  params = [ distro, postgisMajor ]
  result = join(".", slice(split(".", split("+", getPostgisPackage(distro, postgisMajor))[0]), 0, 2))
}
