name: Bake Images

on:
  schedule:
    # Build images once a week, on Mondays
    - cron: 0 8 * * 1
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - testing
          - production
        default: testing
        description: "Choose the environment to bake the target for"

permissions: {}

jobs:
  get_versions:
    name: Get PostgreSQL versions
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      versions: ${{ steps.get_versions.outputs.versions }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Get supported PostgreSQL versions
        id: get_versions
        run: |
          VERSIONS="$(curl -s https://raw.githubusercontent.com/cloudnative-pg/postgres-containers/refs/heads/main/docker-bake.hcl \
            | sed -n '/postgreSQLVersions = \[/,/\]/ s/.*"\([0-9][0-9]*\)[.~][^"]*".*/\1/p' \
            | sort -nu | paste -sd,)"
          echo "PostgreSQL versions: [$VERSIONS]"
          echo "versions=[$VERSIONS]" >> "$GITHUB_OUTPUT"

  Bake:
    name: Bake
    needs: get_versions
    permissions:
      packages: write
      contents: read
      id-token: write
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.get_versions.outputs.versions) }}
    uses: cloudnative-pg/postgres-containers/.github/workflows/bake_targets.yml@dev/316
    with:
      environment: ${{ github.event.inputs.environment }}
      postgresql_version: ${{ matrix.version }}
      target: "postgis"
      bake_files: "./source/docker-bake.hcl,./docker-bake.hcl"
      bake_remote_source: "cloudnative-pg/postgres-containers"
